name: EvaTunaDailyQuest
main: net.evatunadailyquest.salkcoding.main.Main
version: 1.1.3
author: Salk_Coding
api-version: 1.13
depend: [MythicMobs]
commands:
  DailyQuest:
    description: Base command of all commmand in this plugin
    usage: /DailyQuest or /dq or /일퀘 or /일일퀘스트 (Ignore case)
    aliases: [dq,일퀘,일일퀘스트]